<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260812192509 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise_supported_goal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, goal_type VARCHAR(50) NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3ED8A85BE934951A ON exercise_supported_goal (exercise_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_exercise_goal ON exercise_supported_goal (exercise_id, goal_type)');
        $this->addSql('ALTER TABLE exercise_supported_goal ADD CONSTRAINT FK_3ED8A85BE934951A FOREIGN KEY (exercise_id) REFERENCES exercises (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercises DROP supported_goals');
        $this->addSql('ALTER TABLE training_goal DROP CONSTRAINT fk_fdf2e2eea76ed395');
        $this->addSql('COMMENT ON COLUMN training_goal.created_at IS \'\'');
        $this->addSql('ALTER TABLE training_goal ADD CONSTRAINT FK_F346AC6DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_fdf2e2eea76ed395 RENAME TO IDX_F346AC6DA76ED395');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_supported_goal DROP CONSTRAINT FK_3ED8A85BE934951A');
        $this->addSql('DROP TABLE exercise_supported_goal');
        $this->addSql('ALTER TABLE exercises ADD supported_goals JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE training_goal DROP CONSTRAINT FK_F346AC6DA76ED395');
        $this->addSql('COMMENT ON COLUMN training_goal.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE training_goal ADD CONSTRAINT fk_fdf2e2eea76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_f346ac6da76ed395 RENAME TO idx_fdf2e2eea76ed395');
    }
}
