<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260903095257 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE workout_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, trainer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4F11F235A76ED395 ON workout_template (user_id)');
        $this->addSql('CREATE INDEX IDX_4F11F235FB08EDF6 ON workout_template (trainer_id)');
        $this->addSql('CREATE TABLE workout_template_exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_index INT NOT NULL, notes TEXT DEFAULT NULL, template_id INT NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_665529155DA0FB8 ON workout_template_exercise (template_id)');
        $this->addSql('CREATE INDEX IDX_66552915E934951A ON workout_template_exercise (exercise_id)');
        $this->addSql('CREATE TABLE workout_template_exercise_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, set_number INT NOT NULL, reps INT DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, tempo VARCHAR(255) DEFAULT NULL, template_exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98398B98E2CD817E ON workout_template_exercise_set (template_exercise_id)');
        $this->addSql('ALTER TABLE workout_template ADD CONSTRAINT FK_4F11F235A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_template ADD CONSTRAINT FK_4F11F235FB08EDF6 FOREIGN KEY (trainer_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_template_exercise ADD CONSTRAINT FK_665529155DA0FB8 FOREIGN KEY (template_id) REFERENCES workout_template (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_template_exercise ADD CONSTRAINT FK_66552915E934951A FOREIGN KEY (exercise_id) REFERENCES exercises (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_template_exercise_set ADD CONSTRAINT FK_98398B98E2CD817E FOREIGN KEY (template_exercise_id) REFERENCES workout_template_exercise (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout ADD template_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE workout ADD CONSTRAINT FK_649FFB725DA0FB8 FOREIGN KEY (template_id) REFERENCES workout_template (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_649FFB725DA0FB8 ON workout (template_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE workout_template DROP CONSTRAINT FK_4F11F235A76ED395');
        $this->addSql('ALTER TABLE workout_template DROP CONSTRAINT FK_4F11F235FB08EDF6');
        $this->addSql('ALTER TABLE workout_template_exercise DROP CONSTRAINT FK_665529155DA0FB8');
        $this->addSql('ALTER TABLE workout_template_exercise DROP CONSTRAINT FK_66552915E934951A');
        $this->addSql('ALTER TABLE workout_template_exercise_set DROP CONSTRAINT FK_98398B98E2CD817E');
        $this->addSql('DROP TABLE workout_template');
        $this->addSql('DROP TABLE workout_template_exercise');
        $this->addSql('DROP TABLE workout_template_exercise_set');
        $this->addSql('ALTER TABLE workout DROP CONSTRAINT FK_649FFB725DA0FB8');
        $this->addSql('DROP INDEX IDX_649FFB725DA0FB8');
        $this->addSql('ALTER TABLE workout DROP template_id');
    }
}
