<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260902200934 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE training_plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, creator_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2C01C3EA76ED395 ON training_plan (user_id)');
        $this->addSql('CREATE INDEX IDX_D2C01C3E61220EA6 ON training_plan (creator_id)');
        $this->addSql('ALTER TABLE training_plan ADD CONSTRAINT FK_D2C01C3EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_plan ADD CONSTRAINT FK_D2C01C3E61220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout ADD day_number INT DEFAULT NULL');
        $this->addSql('ALTER TABLE workout ADD is_rest_day BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE workout ADD training_plan_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE workout ADD CONSTRAINT FK_649FFB7235A79295 FOREIGN KEY (training_plan_id) REFERENCES training_plan (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_649FFB7235A79295 ON workout (training_plan_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE training_plan DROP CONSTRAINT FK_D2C01C3EA76ED395');
        $this->addSql('ALTER TABLE training_plan DROP CONSTRAINT FK_D2C01C3E61220EA6');
        $this->addSql('DROP TABLE training_plan');
        $this->addSql('ALTER TABLE workout DROP CONSTRAINT FK_649FFB7235A79295');
        $this->addSql('DROP INDEX IDX_649FFB7235A79295');
        $this->addSql('ALTER TABLE workout DROP day_number');
        $this->addSql('ALTER TABLE workout DROP is_rest_day');
        $this->addSql('ALTER TABLE workout DROP training_plan_id');
    }
}
