<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260813105942 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE workout (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(255) NOT NULL, user_id INT NOT NULL, trainer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_649FFB72A76ED395 ON workout (user_id)');
        $this->addSql('CREATE INDEX IDX_649FFB72FB08EDF6 ON workout (trainer_id)');
        $this->addSql('CREATE TABLE workout_exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_index INT NOT NULL, notes TEXT DEFAULT NULL, workout_id INT NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_76AB38AAA6CCCFC9 ON workout_exercise (workout_id)');
        $this->addSql('CREATE INDEX IDX_76AB38AAE934951A ON workout_exercise (exercise_id)');
        $this->addSql('CREATE TABLE workout_exercise_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, set_number INT NOT NULL, reps INT NOT NULL, weight DOUBLE PRECISION NOT NULL, tempo VARCHAR(255) DEFAULT NULL, is_completed BOOLEAN NOT NULL, is_drop_set BOOLEAN NOT NULL, workout_exercise_id INT NOT NULL, parent_set_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5744C044E435DB6B ON workout_exercise_set (workout_exercise_id)');
        $this->addSql('CREATE INDEX IDX_5744C0445FE8CEDE ON workout_exercise_set (parent_set_id)');
        $this->addSql('ALTER TABLE workout ADD CONSTRAINT FK_649FFB72A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout ADD CONSTRAINT FK_649FFB72FB08EDF6 FOREIGN KEY (trainer_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE workout_exercise ADD CONSTRAINT FK_76AB38AAA6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_exercise ADD CONSTRAINT FK_76AB38AAE934951A FOREIGN KEY (exercise_id) REFERENCES exercises (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_exercise_set ADD CONSTRAINT FK_5744C044E435DB6B FOREIGN KEY (workout_exercise_id) REFERENCES workout_exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_exercise_set ADD CONSTRAINT FK_5744C0445FE8CEDE FOREIGN KEY (parent_set_id) REFERENCES workout_exercise_set (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE workout DROP CONSTRAINT FK_649FFB72A76ED395');
        $this->addSql('ALTER TABLE workout DROP CONSTRAINT FK_649FFB72FB08EDF6');
        $this->addSql('ALTER TABLE workout_exercise DROP CONSTRAINT FK_76AB38AAA6CCCFC9');
        $this->addSql('ALTER TABLE workout_exercise DROP CONSTRAINT FK_76AB38AAE934951A');
        $this->addSql('ALTER TABLE workout_exercise_set DROP CONSTRAINT FK_5744C044E435DB6B');
        $this->addSql('ALTER TABLE workout_exercise_set DROP CONSTRAINT FK_5744C0445FE8CEDE');
        $this->addSql('DROP TABLE workout');
        $this->addSql('DROP TABLE workout_exercise');
        $this->addSql('DROP TABLE workout_exercise_set');
    }
}
