<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260813092641 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trainer_trainee_connection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_main BOOLEAN NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trainer_id INT NOT NULL, trainee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9502A1CFB08EDF6 ON trainer_trainee_connection (trainer_id)');
        $this->addSql('CREATE INDEX IDX_9502A1C36C682D0 ON trainer_trainee_connection (trainee_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_trainer_trainee ON trainer_trainee_connection (trainer_id, trainee_id)');
        $this->addSql('ALTER TABLE trainer_trainee_connection ADD CONSTRAINT FK_9502A1CFB08EDF6 FOREIGN KEY (trainer_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trainer_trainee_connection ADD CONSTRAINT FK_9502A1C36C682D0 FOREIGN KEY (trainee_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal_type ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE goal_type ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_goal_type_name RENAME TO UNIQ_92EE128B5E237E06');
        $this->addSql('ALTER INDEX idx_training_goal_type RENAME TO IDX_F346AC6DB4678E6F');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trainer_trainee_connection DROP CONSTRAINT FK_9502A1CFB08EDF6');
        $this->addSql('ALTER TABLE trainer_trainee_connection DROP CONSTRAINT FK_9502A1C36C682D0');
        $this->addSql('DROP TABLE trainer_trainee_connection');
        $this->addSql('ALTER TABLE goal_type ALTER id SET DEFAULT nextval(\'goal_type_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE goal_type ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_92ee128b5e237e06 RENAME TO uniq_goal_type_name');
        $this->addSql('ALTER INDEX idx_f346ac6db4678e6f RENAME TO idx_training_goal_type');
    }
}
