<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210120756 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise_muscle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, activation_level VARCHAR(255) NOT NULL, exercise_id INT NOT NULL, muscle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_865E8C84E934951A ON exercise_muscle (exercise_id)');
        $this->addSql('CREATE INDEX IDX_865E8C84354FDBB4 ON exercise_muscle (muscle_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_exercise_muscle ON exercise_muscle (exercise_id, muscle_id)');
        $this->addSql('ALTER TABLE exercise_muscle ADD CONSTRAINT FK_865E8C84E934951A FOREIGN KEY (exercise_id) REFERENCES exercises (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_muscle ADD CONSTRAINT FK_865E8C84354FDBB4 FOREIGN KEY (muscle_id) REFERENCES muscles (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_muscle DROP CONSTRAINT FK_865E8C84E934951A');
        $this->addSql('ALTER TABLE exercise_muscle DROP CONSTRAINT FK_865E8C84354FDBB4');
        $this->addSql('DROP TABLE exercise_muscle');
    }
}
