<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Tworzy tabelę training_goal dla modułu celów treningowych.
 */
final class Version20260812120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Tworzy tabelę training_goal z relacją do tabeli user';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE training_goal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, goal_type VARCHAR(50) NOT NULL, fitness_level SMALLINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, notes VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FDF2E2EEA76ED395 ON training_goal (user_id)');
        $this->addSql('COMMENT ON COLUMN training_goal.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE training_goal ADD CONSTRAINT FK_FDF2E2EEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE training_goal DROP CONSTRAINT FK_FDF2E2EEA76ED395');
        $this->addSql('DROP TABLE training_goal');
    }
}
