<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260811101929 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE body_part_muscles DROP CONSTRAINT IF EXISTS fk_abdd429774704fc7');
        $this->addSql('DROP TABLE IF EXISTS body_part_muscles');
        $this->addSql('ALTER TABLE muscles DROP CONSTRAINT IF EXISTS fk_2b4821fba430e800');
        $this->addSql('DROP INDEX IF EXISTS idx_2b4821fba430e800');
        $this->addSql('ALTER TABLE muscles DROP COLUMN IF EXISTS body_part_muscles_id');
        $this->addSql('ALTER TABLE muscles ALTER body_part_id SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE body_part_muscles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body_part_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_abdd429774704fc7 ON body_part_muscles (body_part_id_id)');
        $this->addSql('ALTER TABLE body_part_muscles ADD CONSTRAINT fk_abdd429774704fc7 FOREIGN KEY (body_part_id_id) REFERENCES body_parts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE muscles ADD body_part_muscles_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE muscles ALTER body_part_id DROP NOT NULL');
        $this->addSql('ALTER TABLE muscles ADD CONSTRAINT fk_2b4821fba430e800 FOREIGN KEY (body_part_muscles_id) REFERENCES body_part_muscles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_2b4821fba430e800 ON muscles (body_part_muscles_id)');
    }
}
