<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260811094935 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE body_part_muscles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body_part_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ABDD429774704FC7 ON body_part_muscles (body_part_id_id)');
        $this->addSql('ALTER TABLE body_part_muscles ADD CONSTRAINT FK_ABDD429774704FC7 FOREIGN KEY (body_part_id_id) REFERENCES body_parts (id)');
        $this->addSql('ALTER TABLE meseurments DROP CONSTRAINT fk_c3da69fd354fdbb4');
        $this->addSql('ALTER TABLE meseurments ADD CONSTRAINT FK_C3DA69FDA515F27A FOREIGN KEY (body_part_id) REFERENCES body_parts (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_c3da69fd354fdbb4 RENAME TO IDX_C3DA69FDA515F27A');
        $this->addSql('ALTER TABLE muscles ADD body_part_muscles_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE muscles ADD CONSTRAINT FK_2B4821FBA430E800 FOREIGN KEY (body_part_muscles_id) REFERENCES body_part_muscles (id)');
        $this->addSql('CREATE INDEX IDX_2B4821FBA430E800 ON muscles (body_part_muscles_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE body_part_muscles DROP CONSTRAINT FK_ABDD429774704FC7');
        $this->addSql('DROP TABLE body_part_muscles');
        $this->addSql('ALTER TABLE meseurments DROP CONSTRAINT FK_C3DA69FDA515F27A');
        $this->addSql('ALTER TABLE meseurments ADD CONSTRAINT fk_c3da69fd354fdbb4 FOREIGN KEY (body_part_id) REFERENCES muscles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_c3da69fda515f27a RENAME TO idx_c3da69fd354fdbb4');
        $this->addSql('ALTER TABLE muscles DROP CONSTRAINT FK_2B4821FBA430E800');
        $this->addSql('DROP INDEX IDX_2B4821FBA430E800');
        $this->addSql('ALTER TABLE muscles DROP body_part_muscles_id');
    }
}
